import Head from "next/head";
import Sidebar from "../components/Sidebar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Chat App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-row w-screen">
        <div className="flex-3">
          <Sidebar />
        </div>
        <div className="flex-7 flex-row">
          <h1>Hi</h1>
        </div>
      </div>
    </div>
  );
}
